
// Writing prompt bank for the Writing Canvas.
// Category keys mirror the backend (see /assess_entry/): the category is
// sent with the assessment request and changes how the AI grades the entry
// (register, tone, what gets flagged). 'free' is aliased to the backend's
// legacy 'sandbox' key server-side. ~50 prompts per category ({ ko, en, zh });
// book_review is a smaller, book-specific set.

export const WRITING_CATEGORIES = [
  { key: 'free', label: 'Free' },
  { key: 'reflective', label: 'Reflective' },
  { key: 'persuasive', label: 'Persuasive' },
  { key: 'creative', label: 'Creative' },
  { key: 'book_review', label: 'Book review' },
];

export const WRITING_PROMPTS = {
  // ── Reflective — diary, feelings, memories ──
  reflective: [
    { ko: '오늘 감사했던 세 가지를 적어 보세요.', en: 'Write down three things you were grateful for today.', zh: '写下你今天心存感激的三件事。' },
    { ko: '오늘 하루 중 가장 기억에 남는 순간을 묘사해 보세요.', en: 'Describe the most memorable moment of your day.', zh: '描述你今天最难忘的一瞬间。' },
    { ko: '최근에 읽은 책이나 기사에서 인상 깊었던 부분을 써 보세요.', en: 'Write about something that impressed you from a recent book or article.', zh: '写下最近读过的书或文章中让你印象深刻的部分。' },
    { ko: '지금 이 순간 느끼는 감정을 솔직하게 표현해 보세요.', en: 'Express honestly what you are feeling right now.', zh: '坦率地表达你此时此刻的感受。' },
    { ko: '내일 해야 할 일 중 가장 기대되는 것을 써 보세요.', en: 'Write about what you are looking forward to most tomorrow.', zh: '写下你明天最期待的一件事。' },
    { ko: '어린 시절 살던 집을 떠올려 보세요.', en: 'Recall the home you lived in as a child.', zh: '回忆你童年时住过的房子。' },
    { ko: '오늘 나를 웃게 만든 일은 무엇이었나요?', en: 'What made you smile today?', zh: '今天是什么事情让你露出了笑容？' },
    { ko: '최근에 새로 배운 것에 대해 써 보세요.', en: 'Write about something new you learned recently.', zh: '写一写你最近学到的新知识或新技能。' },
    { ko: '요즘 가장 자주 생각하는 고민은 무엇인가요?', en: 'What worry has been on your mind lately?', zh: '你最近最经常烦恼的事情是什么？' },
    { ko: '스트레스를 받을 때 나만의 해소 방법을 소개해 보세요.', en: 'Describe your own way of relieving stress.', zh: '介绍一下你独特的减压方法。' },
    { ko: '올해 이루고 싶은 목표 하나를 자세히 써 보세요.', en: 'Write in detail about one goal you want to achieve this year.', zh: '详细写下一个你今年想要实现的理想目标。' },
    { ko: '가장 좋아하는 계절과 그 이유를 써 보세요.', en: 'Write about your favorite season and why.', zh: '写下你最喜欢的季节以及原因。' },
    { ko: '나에게 소중한 물건 하나를 소개해 보세요.', en: 'Introduce one object that is precious to you.', zh: '介绍一件对你来说非常珍贵的物品。' },
    { ko: '오늘 먹은 음식 중 가장 맛있었던 것을 묘사해 보세요.', en: 'Describe the most delicious thing you ate today.', zh: '描述一下你今天吃过最美味的食物。' },
    { ko: '최근에 만난 사람 중 인상 깊었던 사람에 대해 써 보세요.', en: 'Write about a memorable person you met recently.', zh: '写一写你最近见到的令人印象深刻的人。' },
    { ko: '지금 창밖으로 보이는 풍경을 묘사해 보세요.', en: 'Describe the scenery outside your window right now.', zh: '描述一下你现在透过窗户看到的景色。' },
    { ko: '나의 아침 습관에 대해 써 보세요.', en: 'Write about your morning routine.', zh: '写一写你的晨间习惯。' },
    { ko: '어릴 때 꿈꾸던 직업은 무엇이었나요? 지금과 비교해 보세요.', en: 'What job did you dream of as a child? Compare it with now.', zh: '你小时候梦想的职业是什么？与现在对比一下。' },
    { ko: '요즘 즐겨 듣는 음악과 그 이유를 써 보세요.', en: 'Write about music you enjoy these days and why.', zh: '写一写你最近经常听的音乐及原因。' },
    { ko: '가족 중 한 명에게 하고 싶은 말을 편지처럼 써 보세요.', en: 'Write something you want to say to a family member, like a letter.', zh: '把你想对某位家人说的话像写信一样写下来。' },
    { ko: '최근 일주일 동안 가장 힘들었던 순간은 언제였나요?', en: 'What was the hardest moment of the past week?', zh: '过去这一周里，你最艰难的时刻是什么时候？' },
    { ko: '나를 한 단어로 표현한다면 무엇일까요? 이유도 함께 써 보세요.', en: 'If you described yourself in one word, what would it be? Include the reason.', zh: '如果用一个词来形容你自己，会是什么？并写下原因。' },
    { ko: '오늘 하늘은 어떤 모습이었나요?', en: 'What did the sky look like today?', zh: '今天的蓝色天空是什么样子的？' },
    { ko: '지금까지 받은 선물 중 가장 기억에 남는 것은 무엇인가요?', en: 'What is the most memorable gift you have ever received?', zh: '在你至今收到的礼物中，最难忘的是什么？' },
    { ko: '혼자 있는 시간을 어떻게 보내는지 써 보세요.', en: 'Write about how you spend time alone.', zh: '写一写你是如何度过独处时光的。' },
    { ko: '최근에 후회했던 일과 그로부터 배운 점을 써 보세요.', en: 'Write about something you regretted recently and what you learned from it.', zh: '写一件你最近后悔的事以及从中吸取的教训。' },
    { ko: '나의 하루 중 가장 좋아하는 시간대는 언제인가요?', en: 'What is your favorite time of day?', zh: '在一天之中，你最喜欢哪一个时间段？' },
    { ko: '오랜 친구에게 근황을 전하는 글을 써 보세요.', en: 'Write an update on your life to an old friend.', zh: '写封信给久未谋面的老朋友，聊聊你的近况。' },
    { ko: '요즘 나를 가장 설레게 하는 것은 무엇인가요?', en: 'What excites you most these days?', zh: '最近最让你感到心动或兴奋的事情是什么？' },
    { ko: '지금 살고 있는 동네의 좋은 점과 아쉬운 점을 써 보세요.', en: 'Write about the good and disappointing things about your neighborhood.', zh: '写一写你目前居住的社区的优点和令人遗憾的缺点。' },
    { ko: '최근 꾼 꿈 중에 기억나는 것이 있나요?', en: 'Do you remember any dreams you had recently?', zh: '你最近做的梦里有什么让你记忆犹新的吗？' },
    { ko: "나에게 '집'은 어떤 의미인가요?", en: 'What does "home" mean to you?', zh: '对你来说，“家”意味着什么？' },
    { ko: '올해 가장 잘한 결정은 무엇이라고 생각하나요?', en: 'What do you think was your best decision this year?', zh: '你认为自己今年做出的最正确的决定是什么？' },
    { ko: '요즘 감사하게 느끼는 사람에 대해 써 보세요.', en: 'Write about someone you feel grateful for these days.', zh: '写一个你最近特别想感谢的人。' },
    { ko: '다시 돌아가고 싶은 여행지가 있나요?', en: 'Is there a travel destination you want to return to?', zh: '有没有一个让你想再次到访的旅游胜地？' },
    { ko: '나의 취미가 내 삶에 어떤 영향을 주는지 써 보세요.', en: 'Write about how your hobby affects your life.', zh: '写一写你的业余爱好是如何影响你的生活的。' },
    { ko: '오늘 하루를 색깔로 표현한다면 무슨 색인가요?', en: 'If you expressed today as a color, what color would it be?', zh: '如果用一种颜色来形容你今天的一天，那会是什么颜色？' },
    { ko: '최근에 극복한 어려움에 대해 써 보세요.', en: 'Write about a difficulty you recently overcame.', zh: '写一写你最近克服的一项困难。' },
    { ko: '나이가 들면서 달라진 나의 모습에 대해 써 보세요.', en: 'Write about how you have changed as you have gotten older.', zh: '写一写随着年龄增长，你自己发生的变化。' },
    { ko: '지금 가장 배우고 싶은 것은 무엇인가요?', en: 'What do you most want to learn right now?', zh: '你现在最想学习的东西是什么？' },
    { ko: '나만 아는 우리 동네의 숨은 장소를 소개해 보세요.', en: 'Introduce a hidden place in your neighborhood that only you know.', zh: '介绍一个只有你才知道的、隐藏在我们社区的秘密基地。' },
    { ko: '힘들 때 떠올리는 말이나 문장이 있나요?', en: 'Is there a saying or sentence you recall when times are hard?', zh: '在你深陷困境时，有没有哪句话或哪个句子能给予你力量？' },
    { ko: '요즘의 나에게 필요한 것은 무엇일까요?', en: 'What do you think you need most these days?', zh: '你觉得现在的你最需要的是什么？' },
    { ko: '오늘 만난 사람들과 나눈 대화 중 기억에 남는 것을 써 보세요.', en: 'Write about a memorable conversation you had today.', zh: '写下你今天和遇到的人谈话中，最让你记忆深刻的一句。' },
    { ko: '일 년 뒤의 나에게 짧은 편지를 써 보세요.', en: 'Write a short letter to yourself one year from now.', zh: '写一封简短的信给一年后的自己。' },
    { ko: '최근에 웃음이 났던 사소한 순간을 묘사해 보세요.', en: 'Describe a small moment that made you laugh recently.', zh: '描述一个最近让你不禁会心一笑的微小瞬间。' },
    { ko: '나의 저녁 시간은 보통 어떻게 흘러가나요?', en: 'How does your evening usually go?', zh: '你平时的傍晚到夜间时光通常是怎么度过的？' },
    { ko: '어릴 적 좋아했던 놀이나 게임에 대해 써 보세요.', en: 'Write about a game or activity you loved as a child.', zh: '写一写你小时候特别喜欢的一款游戏或娱乐活动。' },
    { ko: '지금까지 살면서 가장 용감했던 순간은 언제였나요?', en: 'What was the bravest moment of your life so far?', zh: '在你至今的人生里，最勇敢的时刻是什么时候？' },
    { ko: '오늘의 날씨가 나의 기분에 어떤 영향을 줬나요?', en: "How did today's weather affect your mood?", zh: '今天的天气对你的心情产生了什么样的影响？' },
  ],

  // ── Persuasive — opinion, argument, academic register ──
  persuasive: [
    { ko: '인공지능이 인간의 일자리를 대체하는 것에 대해 어떻게 생각하나요?', en: 'What do you think about AI replacing human jobs?', zh: '你如何看待人工智能取代人类工作这一现象？' },
    { ko: '학교에서 교복을 입어야 한다고 생각하나요?', en: 'Do you think students should wear uniforms at school?', zh: '你认为学生在学校应该统一穿校服吗？' },
    { ko: '종이책과 전자책 중 어느 쪽이 더 낫다고 생각하나요?', en: 'Which do you think is better, paper books or e-books?', zh: '你觉得纸质书和电子书哪一个更好？' },
    { ko: '소셜 미디어는 사회에 득이 될까요, 해가 될까요?', en: 'Is social media a benefit or a harm to society?', zh: '社交媒体对社会而言是利大于弊还是弊大于利？' },
    { ko: '대중교통을 무료로 운영해야 한다는 주장에 대해 의견을 써 보세요.', en: 'Give your opinion on the claim that public transportation should be free.', zh: '针对“公共交通应当免费运营”的观点，谈谈你的看法。' },
    { ko: '재택근무가 사무실 근무보다 효율적일까요?', en: 'Is working from home more efficient than working in an office?', zh: '居家办公会比在办公室上班更有效率吗？' },
    { ko: '외국어 교육은 몇 살부터 시작하는 것이 좋을까요?', en: 'At what age should foreign language education begin?', zh: '外语教育从几岁开始比较合适？' },
    { ko: '동물원은 계속 존재해야 할까요?', en: 'Should zoos continue to exist?', zh: '动物园应该继续存在下去吗？' },
    { ko: '환경 보호를 위해 일회용품 사용을 금지해야 할까요?', en: 'Should single-use products be banned to protect the environment?', zh: '为了保护环境，是否应当全面禁止使用一次性用品？' },
    { ko: '시험 성적이 학생의 능력을 제대로 보여 줄 수 있을까요?', en: "Can test scores properly show a student's ability?", zh: '考试成绩真的能准确反映出一个学生的能力吗？' },
    { ko: '유명인의 사생활은 어디까지 보호되어야 할까요?', en: "To what extent should celebrities' private lives be protected?", zh: '公众人物的隐私权应当受到多大程度的保护？' },
    { ko: '어린이의 스마트폰 사용을 제한해야 한다고 생각하나요?', en: "Do you think children's smartphone use should be limited?", zh: '你认为应当限制儿童使用智能手机吗？' },
    { ko: '도시 생활과 시골 생활 중 어느 쪽이 더 행복할까요?', en: 'Which life is happier, city or countryside?', zh: '城市生活与乡村生活，哪一种更让人感到幸福？' },
    { ko: '돈과 시간 중 무엇이 더 중요한 자원일까요?', en: 'Which is the more important resource, money or time?', zh: '金钱和时间，哪一个是更重要的资源？' },
    { ko: '대학 교육은 모든 사람에게 필요할까요?', en: 'Is a university education necessary for everyone?', zh: '大学教育对每个人来说都是必需的吗？' },
    { ko: '게임도 스포츠로 인정받아야 할까요?', en: 'Should gaming be recognized as a sport?', zh: '电子游戏也应当被认可为一项体育运动吗？' },
    { ko: '채식 위주의 식단이 더 윤리적이라고 생각하나요?', en: 'Do you think a plant-based diet is more ethical?', zh: '你认为纯素食或以素食为主的饮食结构更符合道德吗？' },
    { ko: '관광이 지역 사회에 미치는 영향은 긍정적일까요?', en: "Is tourism's impact on local communities positive?", zh: '旅游业对当地社区带来的影响是积极的吗？' },
    { ko: '자율 주행 자동차가 도로를 더 안전하게 만들까요?', en: 'Will self-driving cars make roads safer?', zh: '自动驾驶汽车会让道路交通变得更安全吗？' },
    { ko: '광고가 어린이에게 미치는 영향에 대해 의견을 써 보세요.', en: 'Give your opinion on the impact of advertising on children.', zh: '就广告对儿童产生的影响发表你的看法。' },
    { ko: '주 4일 근무제를 도입해야 한다고 생각하나요?', en: 'Do you think a four-day workweek should be adopted?', zh: '你认为应该引入每周四天工作制吗？' },
    { ko: '온라인 수업이 대면 수업을 대체할 수 있을까요?', en: 'Can online classes replace in-person classes?', zh: '网络授课能够完全取代面对面课堂教学吗？' },
    { ko: '우주 개발에 큰 예산을 쓰는 것이 옳을까요?', en: 'Is it right to spend large budgets on space development?', zh: '将大量预算投入到航天宇宙开发中是正确的吗？' },
    { ko: '역사 교육이 왜 중요한지 자신의 생각을 써 보세요.', en: 'Write your thoughts on why history education is important.', zh: '阐述你对“历史教育为何重要”这一问题的想法。' },
    { ko: '반려동물을 키우는 데 자격이 필요하다고 생각하나요?', en: 'Should qualifications be required for keeping pets?', zh: '你认为饲养宠物需要具备一定的资格认证吗？' },
    { ko: '현금 없는 사회는 좋은 방향일까요?', en: 'Is a cashless society a good direction?', zh: '无现金社会是一个发展的好方向吗？' },
    { ko: '청소년에게 아르바이트 경험이 필요할까요?', en: 'Do teenagers need part-time job experience?', zh: '青少年有必要去体验兼职打工吗？' },
    { ko: '예술 교육이 필수 과목이 되어야 할까요?', en: 'Should arts education be a required subject?', zh: '艺术教育应该成为学校的必修科目吗？' },
    { ko: '인터넷 실명제에 대해 어떻게 생각하나요?', en: 'What do you think about requiring real names on the internet?', zh: '你对网络实名制持有怎样的态度？' },
    { ko: '패스트푸드에 건강세를 부과해야 할까요?', en: 'Should a health tax be imposed on fast food?', zh: '是否应当对快餐食品征收“健康税”？' },
    { ko: '성공에 가장 중요한 것은 재능일까요, 노력일까요?', en: 'Which matters more for success, talent or effort?', zh: '走向成功最关键的因素是天赋还是后天的努力？' },
    { ko: '번역 기술이 발전하면 외국어를 배울 필요가 없어질까요?', en: 'Will language learning become unnecessary as translation technology improves?', zh: '随着翻译技术的发展，我们未来还有必要学习外语吗？' },
    { ko: '쓰레기 분리수거를 법으로 강제해야 할까요?', en: 'Should recycling be enforced by law?', zh: '应该通过法律强制推行垃圾分类吗？' },
    { ko: '어른이 된다는 것은 무엇을 의미한다고 생각하나요? 자신의 기준을 써 보세요.', en: 'What does it mean to become an adult? Explain your standard.', zh: '你认为变成大人意味着什么？请写下你自己的衡量标准。' },
    { ko: '행복은 성적순이 아니라는 말에 동의하나요?', en: 'Do you agree that happiness is not determined by grades?', zh: '你同意“幸福并不取决于成绩排名”这句话吗？' },
    { ko: '전통 시장과 대형 마트, 어느 쪽을 더 지원해야 할까요?', en: 'Which should receive more support, traditional markets or large supermarkets?', zh: '传统集贸市场和大型连锁超市，应该加大对哪一方的扶持力度？' },
    { ko: '아이들에게 용돈을 주는 가장 좋은 방식은 무엇일까요?', en: 'What is the best way to give children an allowance?', zh: '给孩子们零花钱的最好方式是什么？' },
    { ko: '무인 가게가 늘어나는 현상에 대해 의견을 써 보세요.', en: 'Give your opinion on the increase of unmanned stores.', zh: '针对越来越多无人值守店铺出现的现象谈谈你的看法。' },
    { ko: '비판적인 피드백을 수용하는 것은 발전의 필수 요건일까요?', en: 'Is accepting critical feedback a requirement for growth?', zh: '全盘接受批判性的反馈意见是实现自我进步的必要条件吗？' },
    { ko: '결과와 과정 중 무엇이 더 중요하다고 생각하나요?', en: 'Which do you think is more important, results or process?', zh: '你认为结果和过程哪一个更重要？' },
    { ko: '도서관은 앞으로 어떤 역할을 해야 할까요?', en: 'What role should libraries play in the future?', zh: '图书馆在未来应当扮演怎样的角色？' },
    { ko: '유행을 따르는 것은 개성을 잃는 일일까요?', en: 'Does following trends mean losing individuality?', zh: '盲目追随流行趋势是否意味着失去个人独特个性？' },
    { ko: '아침형 인간과 저녁형 인간, 사회는 누구에게 맞춰져 있을까요?', en: 'Morning people vs. night owls — who is society designed for?', zh: '晨型人与夜型人——现代社会更契合哪一类人的作息？' },
    { ko: '실패는 정말 성공의 어머니일까요?', en: 'Is failure really the mother of success?', zh: '失败真的如俗话所说是成功之母吗？' },
    { ko: '공공장소에서의 사진 촬영을 제한해야 할까요?', en: 'Should photography in public places be restricted?', zh: '是否应当限制在公共场所进行拍照摄影？' },
    { ko: '나이 제한이 있는 콘텐츠 규제는 효과적일까요?', en: 'Are age-based content restrictions effective?', zh: '实行基于年龄限制的内容监管机制真的有效吗？' },
    { ko: '지역 축제가 필요한 이유 또는 불필요한 이유를 논해 보세요.', en: 'Argue why local festivals are necessary or unnecessary.', zh: '论述地方性节日庆典存在的必要性或不必要性。' },
    { ko: '모두가 코딩을 배워야 한다는 주장에 동의하나요?', en: 'Do you agree that everyone should learn to code?', zh: '你赞同“人人都应当学习编程”这一主张吗？' },
    { ko: '봉사 활동을 의무화하는 것이 옳을까요?', en: 'Is it right to make volunteer work mandatory?', zh: '将志愿服务活动定为强制性义务的做法正确吗？' },
    { ko: '미래 세대를 위해 지금 우리가 포기해야 할 것은 무엇일까요?', en: 'What should we give up now for future generations?', zh: '为了子孙后代，我们现在应该做出哪些妥协或放弃？' },
  ],

  // ── Creative — story starters, imagery, imagination ──
  creative: [
    { ko: '어느 날 아침, 눈을 떠 보니 모든 소리가 사라져 있었다. 이야기를 이어 써 보세요.', en: 'One morning you woke up and all sound had disappeared. Continue the story.', zh: '某天清晨睁开眼，发现世界所有的声音都消失了。请接着把故事写下去。' },
    { ko: '비 오는 날의 산책을 묘사해 보세요.', en: 'Describe a walk on a rainy day.', zh: '描写一次在下雨天的漫步。' },
    { ko: '오래된 서랍에서 발견한 편지 한 통에 대한 이야기를 써 보세요.', en: 'Write a story about a letter found in an old drawer.', zh: '围绕在陈旧抽屉里发现的一封信写一个故事。' },
    { ko: '시간이 멈춘 도시을 상상해서 묘사해 보세요.', en: 'Imagine and describe a city where time has stopped.', zh: '想象并描绘一座时间完全凝固静止的城市。' },
    { ko: '고양이의 시점에서 하루를 써 보세요.', en: "Write about a day from a cat's point of view.", zh: '以一只猫咪的视角写下它的一天。' },
    { ko: '마지막 지하철을 탄 낯선 두 사람의 대화를 써 보세요.', en: 'Write a conversation between two strangers on the last subway.', zh: '描写在末班地铁上，两个陌生人之间的对话。' },
    { ko: '100년 후의 서울은 어떤 모습일까요?', en: 'What will Seoul look like in 100 years?', zh: '100年后的首尔会呈现出怎样的景象？' },
    { ko: "'문을 열자 바다가 있었다'로 시작하는 글을 써 보세요.", en: 'Write something that begins with "When I opened the door, there was the sea."', zh: '以“推开门，眼前是一片汪洋大海”为开头写一段文字。' },
    { ko: '어릴 적 살던 골목을 배경으로 짧은 이야기를 만들어 보세요.', en: 'Create a short story set in the alley where you grew up.', zh: '以你小时候生活过的小巷为背景，编一个短篇故事。' },
    { ko: '하늘을 나는 능력이 하루만 주어진다면 무엇을 할 건가요?', en: 'If you could fly for just one day, what would you do?', zh: '如果赐予你一天御空飞行的能力，你会去做什么？' },
    { ko: '계절이 딱 하나뿐인 나라의 이야기를 써 보세요.', en: 'Write a story about a country with only one season.', zh: '写一个关于只有一种季节的国度的故事。' },
    { ko: '오래된 사진 한 장을 보고 떠오르는 장면을 써 보세요.', en: 'Write the scene that comes to mind when looking at an old photo.', zh: '凝视一张老照片，写下你脑海中浮现出的画面。' },
    { ko: '자정의 편의점에서 일어난 일을 상상해 보세요.', en: 'Imagine what happened at a convenience store at midnight.', zh: '发挥想象，写一写午夜时分的便利店里发生了什么故事。' },
    { ko: '말을 할 수 있게 된 반려식물과의 첫 대화를 써 보세요.', en: 'Write your first conversation with a houseplant that can suddenly talk.', zh: '写下你和突然开口说话的宠物植物之间的第一次对话。' },
    { ko: '기억을 사고파는 가게가 있다면 어떤 일이 벌어질까요?', en: 'What would happen if there were a shop that buys and sells memories?', zh: '如果世界上存在一家买卖记忆的店铺，会发生什么有趣的事？' },
    { ko: '눈이 내리는 밤의 풍경을 오감으로 묘사해 보세요.', en: 'Describe a snowy night using all five senses.', zh: '调动你的五感，去描绘一个白雪皑皑的夜晚。' },
    { ko: '낯선 도시에서 길을 잃은 여행자의 이야기를 써 보세요.', en: 'Write a story about a traveler lost in an unfamiliar city.', zh: '讲述一个在陌生异界城市中迷失方向的旅行者的故事。' },
    { ko: '매일 같은 꿈을 꾸는 사람의 이야기를 써 보세요.', en: 'Write about a person who has the same dream every night.', zh: '写一个每晚都会做同一个梦的人的故事。' },
    { ko: "'그날따라 이상하게 조용했다'로 시작하는 이야기를 써 보세요.", en: 'Write a story starting with "That day was strangely quiet."', zh: '以“唯独那天，周围静得有些诡异”为开头写一个故事。' },
    { ko: '바닷가 마을의 여름 아침을 묘사해 보세요.', en: 'Describe a summer morning in a seaside village.', zh: '描绘一个海滨小镇的夏日清晨。' },
    { ko: '서로 말이 통하지 않는 두 사람이 친구가 되는 과정을 써 보세요.', en: 'Write about two people becoming friends without a shared language.', zh: '写两个语言不通的人如何一步步建立友谊并成为朋友。' },
    { ko: '하루 동안 투명 인간이 된다면 무엇을 할 건가요?', en: 'What would you do if you were invisible for a day?', zh: '如果让你当一天的隐形人，你会想做什么？' },
    { ko: '오래된 시계탑에 숨겨진 비밀을 상상해 보세요.', en: 'Imagine a secret hidden in an old clock tower.', zh: '想象并揭开一座古老钟楼里隐藏的秘密。' },
    { ko: '첫눈을 처음 보는 아이의 마음을 써 보세요.', en: 'Write the feelings of a child seeing snow for the first time.', zh: '描写一个生平第一次见到初雪的孩子的心情。' },
    { ko: '미래에서 온 택배 상자를 받았다. 이야기를 이어 가 보세요.', en: 'You received a package from the future. Continue the story.', zh: '你收到了一件从未来寄过来的快递包裹。请继续你的故事。' },
    { ko: '도서관에서 밤을 보내게 된 사람의 이야기를 써 보세요.', en: 'Write about someone who ends up spending the night in a library.', zh: '写一个阴差阳错在图书馆度过一夜的人的故事。' },
    { ko: '달빛 아래의 강을 묘사해 보세요.', en: 'Describe a river under moonlight.', zh: '描绘波光粼粼、在月色笼罩下的河流。' },
    { ko: '냄새로 기억을 찾아 주는 탐정의 짧은 사건을 써 보세요.', en: 'Write a short case of a detective who recovers memories through smells.', zh: '写一个凭借气味帮委托人寻回记忆的神探侦破的短篇案件。' },
    { ko: '세상에서 색이 하나씩 사라지기 시작했다. 이야기를 써 보세요.', en: 'Colors have started disappearing from the world, one by one. Write the story.', zh: '世界上的色彩开始按顺序一个接一个地蒸发消失。写下这个故事。' },
    { ko: '산꼭대기 찻집 주인의 하루를 상상해 보세요.', en: 'Imagine a day in the life of a teahouse owner on a mountaintop.', zh: '脑补并描写一位坐落于山巅的茶馆老板的一天。' },
    { ko: '어린 시절의 나와 마주 앉아 대화하는 장면을 써 보세요.', en: 'Write a scene where you sit and talk with your childhood self.', zh: '虚构一个你与童年时期的自己相对而坐、促膝长谈的场景。' },
    { ko: '폭우가 쏟아지는 버스 정류장에서 생긴 일을 써 보세요.', en: 'Write about something that happened at a bus stop in pouring rain.', zh: '写一写在倾盆大雨的公交车站里发生的一幕。' },
    { ko: '주인공이 매일 아침 다른 사람이 되어 깨어난다면?', en: 'What if the main character woke up as a different person every morning?', zh: '如果主角每天清晨醒来都会变成一个完全不同的人？' },
    { ko: '가장 좋아하는 음식이 만들어지는 과정을 시처럼 묘사해 보세요.', en: 'Describe the making of your favorite food like a poem.', zh: '将你最爱美食的烹饪制作过程用诗一般的语言描绘出来。' },
    { ko: '별이 보이지 않는 도시에서 별을 파는 사람의 이야기를 써 보세요.', en: "Write about someone selling stars in a city where stars can't be seen.", zh: '写一个在看不见星光的繁华都市里贩卖星星的人的故事。' },
    { ko: '오래 비어 있던 옆집에 새 이웃이 이사 왔다. 이야기를 써 보세요.', en: 'A new neighbor moved into the long-empty house next door. Write the story.', zh: '隔壁空置了很久的房子搬来了一位神秘的新邻居。请写下这个故事。' },
    { ko: '지도에 없는 섬에 도착한 배의 이야기를 써 보세요.', en: 'Write a story about a ship arriving at an island not on any map.', zh: '写一艘探险船只抵达到一个在任何航海地图上都找不到的孤岛的故事。' },
    { ko: '늦은 밤 라디오에서 내 이름이 흘러나왔다. 이야기를 이어 써 보세요.', en: 'Late at night, your name came out of the radio. Continue the story.', zh: '深夜的收音机广播里突然念出了我的名字。请接龙把故事写下去。' },
    { ko: '할머니의 오래된 요리책에 적힌 이상한 메모에 대해 써 보세요.', en: "Write about a strange note found in grandmother's old cookbook.", zh: '写一写在外婆流传下来的陈旧食谱里发现的一张诡异便签。' },
    { ko: '소리로만 이루어진 세상을 묘사해 보세요.', en: 'Describe a world made only of sound.', zh: '描绘一个仅由纯粹的声音构成的世界。' },
    { ko: '기차 창밖으로 스쳐 가는 풍경을 묘사해 보세요.', en: 'Describe the scenery passing by a train window.', zh: '描绘从火车车窗外飞速掠过的风景。' },
    { ko: '매일 밤 도시의 불빛을 끄고 다니는 사람의 정체를 상상해 보세요.', en: "Imagine the identity of the person who turns off the city's lights every night.", zh: '设想一下那个每晚在都市各个角落默默熄灭路灯的人的真实身份。' },
    { ko: '잃어버린 우산이 주인을 찾아 돌아오는 이야기를 써 보세요.', en: 'Write a story about a lost umbrella finding its way back to its owner.', zh: '编织一个关于一把被遗忘的雨伞历经千辛万苦寻回主人的童话故事。' },
    { ko: '사계절이 하루 만에 지나가는 날을 상상해 보세요.', en: 'Imagine a day when all four seasons pass in twenty-four hours.', zh: '想象充满戏剧性的一天，春夏秋冬在24小时之内轮番上演。' },
    { ko: '편지를 배달하는 비둘기의 마지막 임무를 써 보세요.', en: "Write about a mail pigeon's final mission.", zh: '描写一只负责传书的信鸽所执行的最后一项秘密任务。' },
    { ko: '아무도 없는 놀이공원의 밤을 묘사해 보세요.', en: 'Describe a night at an empty amusement park.', zh: '描绘深夜空无一人的游乐园场景。' },
    { ko: '목소리를 잃은 가수가 새로운 꿈을 찾는 이야기를 써 보세요.', en: 'Write about a singer who lost their voice finding a new dream.', zh: '讲述一位失声的歌手如何寻找人生新方向与梦想的故事。' },
    { ko: '두 도시를 잇는 아주 긴 다리 위에서 벌어진 일을 써 보세요.', en: 'Write about something that happened on a very long bridge connecting two cities.', zh: '写一写在一条横跨并连接两座大都市的宏伟长桥上发生的事。' },
    { ko: "'십 년 만에 그 카페 문을 다시 열었다'로 시작해 보세요.", en: 'Start with "After ten years, I opened that café door again."', zh: '以“时隔整整十年，我再次推开了那家咖啡馆的大门”为开头。' },
    { ko: '세상의 모든 시계가 5분씩 느려졌다. 무슨 일이 벌어질까요?', en: 'Every clock in the world became five minutes slow. What happens?', zh: '倘若世界上所有的时钟都离奇地慢了5分钟，会发生什么连锁反应？' },
  ],

  // ── Free — free writing, no pressure (backend alias: sandbox) ──
  free: [
    { ko: '오늘 하루를 자유롭게 적어 보세요.', en: 'Write freely about your day.', zh: '自由地记录一下你今天的一天。' },
    { ko: '지금 머릿속에 떠오르는 것을 그대로 써 보세요.', en: 'Write down exactly what comes to mind right now.', zh: '把你现在脑子里蹦出来的任何想法原封不动地写下来。' },
    { ko: '가장 좋아하는 음식 세 가지를 소개해 보세요.', en: 'Introduce your three favorite foods.', zh: '介绍三款你最钟爱的美食。' },
    { ko: '주말에 하고 싶은 일을 나열해 보세요.', en: 'List things you want to do this weekend.', zh: '列出你这周末想要完成或体验的事情清单。' },
    { ko: '요즘 자주 쓰는 한국어 단어 다섯 개로 짧은 글을 써 보세요.', en: 'Write a short piece using five Korean words you use often these days.', zh: '用你最近经常用到的五个韩语单词写一篇短文。' },
    { ko: '내 방을 묘사해 보세요.', en: 'Describe your room.', zh: '描述一下你的房间。' },
    { ko: '좋아하는 영화나 드라마를 추천하는 글을 써 보세요.', en: 'Write a recommendation for a movie or drama you like.', zh: '写一篇推荐你喜欢的某部电影或电视剧的推介文。' },
    { ko: '오늘 들은 노래에 대해 써 보세요.', en: 'Write about a song you heard today.', zh: '聊聊你今天听过的一首歌。' },
    { ko: '나의 버킷 리스트 다섯 가지를 써 보세요.', en: 'Write five things on your bucket list.', zh: '写下你人生愿望清单（Bucket List）中的五项。' },
    { ko: '냉장고에 있는 재료로 만들 수 있는 요리를 설명해 보세요.', en: "Explain a dish you could make with what's in your fridge.", zh: '设计并说明一道可以用你家冰箱现有食材做出来的料理。' },
    { ko: '최근에 산 물건에 대해 써 보세요.', en: 'Write about something you bought recently.', zh: '写一写你最近剁手购买的物件。' },
    { ko: '좋아하는 카페나 장소를 소개해 보세요.', en: 'Introduce a café or place you like.', zh: '介绍一间你钟意的咖啡馆或一个你爱去的地方。' },
    { ko: '이번 주의 날씨를 일기 예보처럼 써 보세요.', en: "Write this week's weather like a forecast.", zh: '模仿天气预报的口吻来写一写本周的天气趋势。' },
    { ko: '나의 완벽한 하루를 계획해 보세요.', en: 'Plan your perfect day.', zh: '规划在你心目中堪称完美的一天。' },
    { ko: '한국어를 배우면서 재미있었던 순간을 써 보세요.', en: 'Write about a fun moment while learning Korean.', zh: '分享你在学习韩语的过程中觉得最有趣的一个瞬间。' },
    { ko: '지금 들리는 소리에 귀를 기울이고 들리는 것을 써 보세요.', en: 'Listen closely and write down what you hear right now.', zh: '屏息静听你周围当下的声音，并把听到的动静写下来。' },
    { ko: '좋아하는 운동이나 활동에 대해 써 보세요.', en: 'Write about a sport or activity you enjoy.', zh: '介绍一项你日常热衷的运动或户外活动。' },
    { ko: '오늘의 할 일 목록을 쓰고 하나씩 설명해 보세요.', en: "Write today's to-do list and explain each item.", zh: '列出你今天的待办事项（To-do list）并逐一简单说明。' },
    { ko: '최근에 찍은 사진 한 장을 글로 설명해 보세요.', en: 'Describe a recent photo you took in words.', zh: '用文字细腻地描绘一张你最近拍摄的照片。' },
    { ko: '나의 가방 속에 들어 있는 물건들을 소개해 보세요.', en: 'Introduce the things inside your bag.', zh: '翻翻你的随身包包，介绍一下里面的随身物品。' },
    { ko: '자주 가는 식당의 메뉴를 소개해 보세요.', en: 'Introduce the menu of a restaurant you often visit.', zh: '推介一家你经常光顾的餐馆的菜单。' },
    { ko: '어제와 오늘의 다른 점을 세 가지 써 보세요.', en: 'Write three differences between yesterday and today.', zh: '总结并写出昨天和今天之间的三个不同点。' },
    { ko: '좋아하는 색에 대한 생각을 자유롭게 써 보세요.', en: 'Write freely about your favorite color.', zh: '围绕你最喜欢的颜色随笔谈谈你的看法。' },
    { ko: '아무 단어나 하나 골라 그 단어로 시작하는 글을 써 보세요.', en: 'Pick any word and write something that starts with it.', zh: '信手拈来任意一个词，然后写一段以该词开头的文字。' },
    { ko: '나의 일주일 루틴을 요일별로 써 보세요.', en: 'Write your weekly routine day by day.', zh: '按周一到周日的顺序，写一写你的一周日常惯例。' },
    { ko: '최근 인터넷에서 본 재미있는 것을 써 보세요.', en: 'Write about something fun you saw online recently.', zh: '写一写你最近在网上冲浪时刷到的趣事。' },
    { ko: '지금 마시고 있는 음료, 또는 마시고 싶은 음료에 대해 써 보세요.', en: "Write about the drink you're having, or the one you want.", zh: '聊聊你现在手边正在喝的、或者现在特别渴望喝到的饮品。' },
    { ko: '휴대폰 배경 화면에 대해 이야기해 보세요.', en: "Talk about your phone's wallpaper.", zh: '聊聊你的手机壁纸有什么故事或寓意。' },
    { ko: '좋아하는 간식 순위를 매기고 이유를 써 보세요.', en: 'Rank your favorite snacks and explain why.', zh: '给你最喜欢的零食排个名次，并写下上榜理由。' },
    { ko: '오늘 입은 옷을 묘사해 보세요.', en: "Describe what you're wearing today.", zh: '描述一下你今天一整天的穿搭 OOTD。' },
    { ko: '한국에 가면 꼭 해 보고 싶은 것들을 써 보세요.', en: 'Write things you definitely want to do in Korea.', zh: '写下如果以后去韩国旅游，你雷打不动必须要去体验的事项。' },
    { ko: '나의 이름에 대한 이야기를 써 보세요.', en: 'Write the story of your name.', zh: '讲述一个关于你名字来历或含义的故事。' },
    { ko: '요즘 배우고 있는 것에 대해 자유롭게 써 보세요.', en: "Write freely about something you're learning these days.", zh: '针对你最近正在钻研学习的新领域畅所欲言。' },
    { ko: '5분 동안 멈추지 말고 아무거나 써 보세요.', en: 'Write anything for five minutes without stopping.', zh: '计时五分钟，期间笔尖不要停，随便写点什么都好。' },
    { ko: '좋아하는 계절 음식을 소개해 보세요.', en: 'Introduce your favorite seasonal food.', zh: '介绍一款你情有独钟的季节限定美食。' },
    { ko: '우리 집 근처에서 들리는 소리들을 써 보세요.', en: 'Write about the sounds near your home.', zh: '记录下在我们家附近能听到的各种人间烟火音。' },
    { ko: '최근에 본 꿈 또는 상상한 것을 자유롭게 써 보세요.', en: 'Write freely about a recent dream or something you imagined.', zh: '自由书写你最近做过的一个梦或是一段天马行空的想象。' },
    { ko: '나에게 하루가 30시간이라면 무엇을 할까요?', en: 'If your day had 30 hours, what would you do?', zh: '如果一天突然延长到了30个小时，你会用多出来的5小时干什么？' },
    { ko: '좋아하는 유튜브 채널이나 팟캐스트를 소개해 보세요.', en: 'Introduce a YouTube channel or podcast you like.', zh: '安利一个你平时爱看的YouTube频道或爱听的播客。' },
    { ko: '오늘 하루를 세 문장으로 요약해 보세요.', en: 'Summarize your day in three sentences.', zh: '用言简意赅的三句话总结你今天的经历。' },
    { ko: '내가 자주 쓰는 앱 세 가지를 소개해 보세요.', en: 'Introduce three apps you use often.', zh: '介绍三款你手机里高频打开使用的宝藏App。' },
    { ko: '다음 여행 계획, 또는 상상의 여행을 써 보세요.', en: 'Write about your next trip, real or imagined.', zh: '规划你的下一次旅行日程，哪怕是一次脑补的幻想旅行也行。' },
    { ko: '내 책상 위에 있는 물건들을 묘사해 보세요.', en: 'Describe the things on your desk.', zh: '描绘一下你办公桌或书桌上错落码放的物件。' },
    { ko: '최근에 만들었거나 먹은 요리의 과정을 써 보세요.', en: 'Write the process of a dish you recently made or ate.', zh: '梳理并写下你最近亲自下厨做过、或是品尝过的一道菜的烹饪过程。' },
    { ko: '지금 기분을 날씨로 표현해 보세요.', en: 'Express your current mood as weather.', zh: '如果用天气来指代，你此刻的心情是晴是雨？' },
    { ko: '좋아하는 명언이나 속담에 대해 써 보세요.', en: 'Write about a quote or proverb you like.', zh: '写一写你奉为座右铭的一句名言或谚语。' },
    { ko: '어릴 적 사진 속의 나를 설명해 보세요.', en: 'Describe yourself in a childhood photo.', zh: '端详一张童年旧照，描述一下当年的那个小不点。' },
    { ko: '이번 달에 있었던 일을 뉴스 기사처럼 써 보세요.', en: 'Write about something from this month like a news article.', zh: '把本月发生在你身上的某件事像撰写严肃新闻报道一样写出来。' },
    { ko: '내가 좋아하는 한국어 단어와 그 이유를 써 보세요.', en: 'Write about your favorite Korean word and why.', zh: '写一个你最喜欢的韩语单词，并附上倾心的原因。' },
    { ko: '아무 주제나 골라서 자유롭게 써 보세요. 오늘은 무엇이든 좋아요.', en: 'Pick any topic and write freely — today, anything goes.', zh: '随便挑一个你顺眼的主题自由书写吧。今天无拘无束，写什么都行。' },
  ],

  // ── Book review — about the book you're reading ──
  book_review: [
    { ko: '지금 읽고 있는 책의 줄거리를 간단히 요약해 보세요.', en: "Briefly summarize the plot of the book you're reading.", zh: '简明扼要地概括一下你目前正在阅读的书籍的故事梗概。' },
    { ko: '가장 인상 깊었던 장면과 그 이유를 써 보세요.', en: 'Write about the most memorable scene and why.', zh: '写一写整本书里最让你动容或震动的名场面及原因。' },
    { ko: '주인공의 성격을 묘사하고 실제로 만나면 어떨지 상상해 보세요.', en: "Describe the main character's personality and imagine meeting them.", zh: '刻画一下主角的性格特质，并设想现实中若与他相遇会是怎样的情景。' },
    { ko: '이 책의 제목이 내용과 어울린다고 생각하나요?', en: "Do you think the book's title fits its content?", zh: '你觉得这本书的书名和它的核心内容契合匹配吗？' },
    { ko: '작가가 전하려는 메시지는 무엇이라고 생각하나요?', en: 'What message do you think the author is trying to convey?', zh: '你认为作者字里行间想要向读者传达的终极主旨是什么？' },
    { ko: '마음에 남은 문장을 하나 골라 그 이유를 써 보세요.', en: 'Pick one sentence that stayed with you and explain why.', zh: '摘录一句让你久久不能忘怀的书中金句，并阐明理由。' },
    { ko: '이야기의 배경이 되는 시대와 장소를 설명해 보세요.', en: 'Describe the time and place where the story is set.', zh: '向大家交代并描述故事发生的时代背景和地理舞台。' },
    { ko: '등장인물 중 한 명에게 편지를 써 보세요.', en: 'Write a letter to one of the characters.', zh: '给书中的某一位登场人物写一封跨越时空的信。' },
    { ko: '이 책을 친구에게 추천한다면 어떻게 소개할 건가요?', en: 'How would you introduce this book if recommending it to a friend?', zh: '如果要把这本书安利给身边的挚友，你会准备怎么去介绍它？' },
    { ko: '예상과 다르게 흘러간 부분이 있었나요?', en: 'Was there a part that went differently than you expected?', zh: '书中是否有哪一段情节的发展完全打破了你的既定预判？' },
    { ko: '이야기의 결말을 바꿀 수 있다면 어떻게 바꾸고 싶나요?', en: 'If you could change the ending, how would you?', zh: '如果你拥有改写故事结局的神圣权力，你想怎么去重写它？' },
    { ko: '주인공의 선택에 동의하나요? 자신이라면 어떻게 했을까요?', en: "Do you agree with the protagonist's choice? What would you have done?", zh: '你认同主角在关键时刻做出的抉择吗？换作是你在那个处境下会怎么做？' },
    { ko: '이 책에서 새로 배운 단어나 표현을 정리해 보세요.', en: 'Note new words or expressions you learned from this book.', zh: '归纳整理一下你通过阅读这本书新习得的生词或高级表达。' },
    { ko: '책 속 갈등이 어떻게 해결되는지 설명해 보세요.', en: 'Explain how the conflict in the book is resolved.', zh: '梳理并分析书中的核心矛盾和戏剧冲突最终是如何被化解平息的。' },
    { ko: '이 책의 분위기를 날씨나 계절에 비유해 보세요.', en: "Compare the book's mood to weather or a season.", zh: '若把这本书的基调和氛围拟人化，它更像哪种天气或哪个季节？' },
    { ko: '등장인물들의 관계를 설명해 보세요.', en: 'Describe the relationships between the characters.', zh: '理一理书中交织在一起的人物关系网。' },
    { ko: '지금까지 읽은 부분에서 가장 궁금한 점은 무엇인가요?', en: "What are you most curious about in what you've read so far?", zh: '在目前已经读完的章节里，最让你抓心挠肝、充满好奇的悬念是什么？' },
    { ko: '이 이야기가 영화가 된다면 어떤 장면이 하이라이트일까요?', en: 'If this story became a movie, which scene would be the highlight?', zh: '如果这部作品被影视化改编搬上大银幕，哪一幕会是整部电影的高光名场面？' },
    { ko: '작가의 문체에 대해 느낀 점을 써 보세요.', en: "Write your impressions of the author's writing style.", zh: '评价或谈谈你对这位作家笔触文风的直观感受。' },
    { ko: '이 책을 읽고 나의 생각이나 감정이 어떻게 달라졌나요?', en: 'How did this book change your thoughts or feelings?', zh: '合上书本，这本书让你的思维方式或情感状态发生了怎样的蜕变与化学反应？' },
  ],
};

// Reverse lookup: find the {ko, en, zh} pair for a stored prompt string, so an
// existing entry's chosen prompt can render with its translation.
export const findPromptByKo = (ko) => {
  if (typeof ko !== 'string' || !ko.trim()) return null;
  for (const list of Object.values(WRITING_PROMPTS)) {
    const match = list.find((p) => p.ko === ko);
    if (match) return match;
  }
  return null;
};
