import { Animated, StyleSheet, View } from 'react-native';

// Semi-transparent lighting overlay generated by scripts/generateBookGloss.js.
// Stretched over any cover it fakes a hardcover: spine dip, hinge highlight,
// rim light, and bottom shading.
const GLOSS_SOURCE = require('../../assets/book-gloss.png');

// Wraps a book cover (any children sized to width/height) with a drop shadow
// and the gloss overlay. glossOpacity/shadowOpacity accept plain numbers or
// Animated values so a carousel can fade the 3D treatment in and out.
const Book3D = ({
    width,
    height,
    radius = 2,
    glossOpacity = 1,
    shadowOpacity = 1,
    style,
    children,
}) => (
    <View style={[{ width, height }, style]}>
        <Animated.View
            pointerEvents="none"
            style={[
                styles.shadow,
                { borderRadius: radius, opacity: shadowOpacity },
            ]}
        />
        <View style={[styles.clip, { borderRadius: radius }]}>
            {children}
            <Animated.Image
                pointerEvents="none"
                source={GLOSS_SOURCE}
                fadeDuration={0}
                resizeMode="stretch"
                style={[styles.gloss, { opacity: glossOpacity }]}
            />
        </View>
    </View>
);

const styles = StyleSheet.create({
    shadow: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: '#0b0d12',
        shadowColor: '#000000',
        shadowOpacity: 0.24,
        shadowRadius: 18,
        shadowOffset: { width: 0, height: 12 },
        elevation: 12,
    },
    clip: {
        flex: 1,
        overflow: 'hidden',
    },
    gloss: {
        ...StyleSheet.absoluteFillObject,
        width: undefined,
        height: undefined,
    },
});

export default Book3D;
